import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import NextTopLoader from 'nextjs-toploader';
import { auth } from "@/auth";
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FundNepal",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar session={session} />
          <NextTopLoader color="#6059c2" showSpinner={false} />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
